name: TESTING
description: test
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2020-09-29"
api_version: 1

environment_variables:
  DATA_LOCATION:
    default: "data/churn_prototype"
    description: >-
      Relative path that will be used to store the data used for this prototype.
      This should be a location you have write access to, and which is suitable for non-production data.
