name: TESTING
description: test
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2020-09-29"
api_version: 1

environment_variables:
  DATA_LOCATION:
    default: "data/churn_prototype"
    description: >-
      Testing script

  - type: create_job
    name: Script1
    entity_label: script1
    script: script1.py
    arguments: None
    short_summary: job for script1
    kernel: python3

  - type: run_job
    entity_label: script1
    short_summary: run script1
    long_summary: >-
      Running script1

  - type: create_job
    name: Script2
    entity_label: script2
    script: script1.py
    arguments: None
    short_summary: job for script2
    kernel: python3

  - type: run_job
    entity_label: script2
    short_summary: run script2
    long_summary: >-
      Running script2